college_name=input("Enter your College name: ")
course=input("Enter your Course name: ")
year=int(input("Enter your currunt Year: "))
print("College Name: ",college_name)
print("Course Name: ",course)
print("Year: ",year)